remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: [Morgan T. Chidester]
description: [I am an Astrophysics graduate student at Arizona State University.  I am a theorist, focusing on stellar evolution, primarily with White Dwarf seismology. My research involves using seismic signatures from white dwarfs to constrain their interiors which encapsulate their evolution history.]
